# Generated by Django 2.2.1 on 2019-06-04 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkTitle', models.CharField(default='A Site', max_length=100)),
                ('urlToBeShortened', models.CharField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('shortenedUrl', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name_plural': 'Shorten URL',
            },
        ),
    ]
